### ISSUE TITLE
MongoDB Connection URL

### ISSUE THREAD

**Issue by deepabhyudaya** [LWG13/contact-server#1]
> contact-server/connect.cjs

A generalized MongoDB url looks like this 

`mongoose.connect('mongodb://username:password@host:port/database?options...')`

It's a good practice to use environment variables for database connection urls, as people with bad intentions could cause harm to your database once they have the access to it.

**Comment by LWG13** [comment]
thank you, i will fixing it

Vào 19:42, CN, 17 Th11, 2024 Abhyudaya ***@***.***> đã viết:
